export const Paths = {
    home: '/',
    about: '/about',
    services: '/services',
    destinations: '/destinations',
    destinationCreate: '/destinations/create',
    packages: '/packages',
    packageCreate: '/packages/create',
    packageDetails: '/packages/:id',
    reviewDelete: '/reviews/delete/:reviewId',
    reviewEdit: '/reviews/edit/:reviewId',
    booking: '/booking',
    processing: '/process',
    team: '/team',
    contact: '/contact',
    login: '/login',
    register: '/register',
    logout: '/logout',
    profile: '/profile',
    other: '*'
}